[package]
name = "wt_blk_macro"
version = "0.0.0"
authors = ["FlareFlo <mail@flareflo.dev>"]
description = ""
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "1.0"

