[package]
name = "wt_blk"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Parser for Json-like files blk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "^1"
serde = {version = "^1", features = ["serde_derive", "rc"]}
thiserror = "^1"
zstd = "0.12.3+zstd.1.5.2"
lazy_static = "^1.4.0"
rayon = "1.6"
tracing = "^0.1.37"
hex = "^0.4.3"
memmap2 = "0.5.10"
color-eyre = "^0.6"

#[profile.test]
#opt-level = 3
#lto = "fat"
#debug = true

[profile.bench]
opt-level = 3
lto = true
debug = true

[profile.release]
opt-level = 3
lto = true
debug = true

[dev-dependencies]
pretty_assertions = "1.3.0"
criterion = "0.4.0"

[[bench]]
name = "blk"
harness = false
