[package]
name = "wt_blk"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Parser and unpacker for the BLK file format"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json ={version = "^1", features = ["preserve_order", "float_roundtrip"]}
serde = {version = "^1", features = ["serde_derive", "rc"]}
thiserror = "^1"
zstd = "0.12.3+zstd.1.5.2"
lazy_static = "^1.4.0"
rayon = "1.6"
tracing = "^0.1.37"
hex = "^0.4.3"
memmap2 = "0.5.10"
color-eyre = "^0.6"
strum = { version = "0.25.0", default-features = false, features = ["derive"] }

[profile.test]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
lto = true
debug = true

[profile.release]
opt-level = 3
lto = true
debug = true

[dev-dependencies]
pretty_assertions = "1.3.0"
#criterion = "0.4.0"

#[[bench]]
#name = "blk"
#harness = false
