[package]
name = "wt_blk_pybindings"
version = "0.1.6"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
wt_blk = { path = "../" }
