[package]
name = "wt_blk_pybindings"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
wt_blk = { path = "../" }
