[package]
name = "wt_vromf"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.12.3+zstd.1.5.2"
tracing = "^0.1.37"
thiserror = "^1"