name: Render drawio

on:
  push:
    paths:
      - "charts"
    branches: [ "master" ]

permissions:
  actions: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Convert diagram to png
        uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
            source: charts/blk_conversions.drawio
            destination: blk_conversions.svg

      - name: Push to assets branch
        uses: actions-js/push@master
        with:
          branch: "assets"
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}