name: Render drawio

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Convert diagram to png
        uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
            source: charts/blk_conversions.drawio
            destination: blk_conversions.svg

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blk_conversions
          path: blk_conversions.svg